### PR TITLE
parallel json parsing

### PR DESCRIPTION
**Pull request by dimatr**
On a 2.2 GB test this drops the JSONparser time from 3 min to 30 sec

### CODE REVIEW

**Review by josiahseaman — CHANGES_REQUESTED** [review]
`python -m pip install ray`
Collecting ray
  ERROR: Could not find a version that satisfies the requirement ray (from versions: none)
ERROR: No matching distribution found for ray

There's clearly a repo here: https://pypi.org/project/ray/ I've updated pip.  Perhaps this is pypy only distro?  Could you please give me more info on ray install compatibility and whether we'll be able to build it into the requirements.txt or some other automated solution?

**Comment by josiahseaman** [comment]
The issue appears to be that wheels are only built for Linux and MacOS, but I'm testing on a Windows machine.  The lack of support makes sense really, but it should at least be noted this would be the first departure of Pantograph from being cross-platform compatible.  Would you mind writing an OS switch and local import instead?

https://ray.readthedocs.io/en/latest/installation.html

**Comment by lomereiter** [comment]
Also consider using an OS-independent library (joblib?)

**Comment by subwaystation** [comment]
Do we really need support for Windows? 
There is no Windows support for e.g. `odgi`, too. 
We will have our docker pipeline, so as long as docker is available, the whole thing will work out.

**Comment by dimatr** [comment]
Please check now. The current change works on Linux and Windows

**Comment by subwaystation** [comment]
Reading in the data on a 28 core machine is much faster now! Thanks @dimatr .

Just one minor thing: How about a parameter where users can specify the number of cores to use?

**Comment by dimatr** [comment]
I will add one new parameter --parallel-cores with default os.cpu_count()

**Comment by dimatr** [comment]
should be ready now, please check

**Pull request merged**
