### PR TITLE
Zooming: separate directories: Fixes#12 and adds to #16 v11 and v12 

### PR DESCRIPTION
**Pull request by mandosoft**
Had trouble testing on list of files using the run configuration and just chaining `-j <path name>` 
`-j <path_name_2>`  etc. I'm sure there's a better way to do this. 

JSON version is now updated to 12.

### CODE REVIEW

**Review by josiahseaman — CHANGES_REQUESTED** [review]
I'm seeing some red flags in https://github.com/graph-genome/component_segmentation/pull/28/files Look at the File Filter, it appears to list hundreds of log file extensions.  There's also PYC etc. Check your .gitignore and make sure no unnecessary files are checked in.  I know Mark Seaman had a bad push earlier that I had to delete, so it may be a history issue, but I'd like you to check your git status first.  Not every file you have should be checked in.  Definitely don't use `git add * -f`.  It would be a big victory to get zooming started, but we've got to do it right.  Thanks for all your hard work!

((Changing the log file names to always end in .log will make .gitignore more effective.))

**Comment by josiahseaman** [comment]
I think automatic detection of input files given a prefix is a must, since we may have 30 zoom levels in the end. from glob import glob is great for that.

**Comment by mandosoft** [comment]
Not sure how it dumped so many log files but likely due to the w1.json. I'll rework this with glob and recommit with just the .py files. Thanks!

**Comment by josiahseaman** [comment]
Let's close this PR since your new plan is to make a fresh branch from master and manually edit in your fixes.  Remember, each zoom level should get it's own subdirectory inside the "graph_name" subdirectory and bin2file.json will be sitting in "graph_name" with an index to all the files.  I'd say sequence only needs to be listed once for bin_width=1, so it can sit next to bin2file.json and only the width=1 zoom layer need reference "fasta_file" entries.

**Pull request closed without merging**
